version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "homeassistant"
        update-types: ["version-update:semver-patch"]
