name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
template: |
  See the [CHANGELOG.md]($REPOSITORY/blob/master/CHANGELOG.md) for more
  information.

  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
